### ISSUE TITLE
ToDo Application crash during startup

### ISSUE THREAD

**Issue by SAGARSURI** [commonsguy/cw-androidarch#5]
I tried running the app. But its crashing due to some layout issue. Here is the logcat:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.commonsware.android.mvi/com.commonsware.android.todo.ui.MainActivity}: android.view.InflateException: Binary XML file line #34: Binary XML file line #34: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.view.InflateException: Binary XML file line #34: Binary XML file line #34: Error inflating class <unknown>
     Caused by: android.view.InflateException: Binary XML file line #34: Error inflating class <unknown>
     Caused by: android.os.StrictMode$StrictModeViolation: policy=262207 violation=2
        at android.os.StrictMode.executeDeathPenalty(StrictMode.java:1684)
        at android.os.StrictMode.-wrap3(Unknown Source:0)
        at android.os.StrictMode$AndroidBlockGuardPolicy.handleViolation(StrictMode.java:1677)
        at android.os.StrictMode$AndroidBlockGuardPolicy.handleViolationWithTimingAttempt(StrictMode.java:1500)
        at android.os.StrictMode$AndroidBlockGuardPolicy.startHandlingViolationException(StrictMode.java:1470)
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1439)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:837)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:634)
        at java.lang.String.valueOf(String.java:2827)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:194)
        at java.lang.String.valueOf(String.java:2827)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:94)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1901)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2579)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2652)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:408)
        at android.app.Activity.setContentView(Activity.java:2654)
        at com.commonsware.android.todo.ui.MainActivity.onCreate(MainActivity.java:34)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by commonsguy** [comment]
I cannot reproduce the problem. There is nothing in any layout of this project that should cause a `StrictMode` violation, just for inflating the layout. Something is strange about your environment.

If you want, comment out the `StrictMode` code in the `com.commonsware.android.todo.App` class, or change it to not use `penaltyDeath()` for debug builds.
